remove the pointless space before the elements in statusbar.

diff --git a/.dwm/bars/w0ng_bash/statusbar b/.dwm/bars/w0ng_bash/statusbar
--- a/.dwm/bars/w0ng_bash/statusbar
+++ b/.dwm/bars/w0ng_bash/statusbar
@@ -8,9 +8,7 @@
 # http://archlinux.me/w0ng/2012/05/01/dwm-a-pretty-statusbar/
 
 # nw interface & stats dir:
-defaultInterface="eth0"
 nwInterfaceStats=""
-connectedInterfaceFile="/tmp/connected_default_if.dat"
 
 # mail constants:
 PREFIXES=( \
@@ -50,15 +48,6 @@ sep_solid="\uE01A"
 sep_line="\uE01B"
 sep_bar="\uE020"
 
-find_connected_if() {
-  if [[ -f "$connectedInterfaceFile" ]]; then
-      interface="$(cat $connectedInterfaceFile)"
-  else
-      interface="$defaultInterface"
-  fi
-
-  nwInterfaceStats="/sys/class/net/$interface/statistics"
-}
 
 print_song_info() {
   mpc_query="$(mpc current -f '[[[[%artist% \uE01B ]%title%]]|[%file%]]' | head -c 75)"
@@ -135,63 +124,73 @@ convertTxRates() {
     fi
 }
 
+
+# import common:
+if [[ -f "$_SCRIPTS_COMMONS" && -r "$_SCRIPTS_COMMONS" ]]; then
+    source "$_SCRIPTS_COMMONS"
+else
+    echo -e "\nError: common file \"$_SCRIPTS_COMMONS\" not found. Abort."
+    exit 1
+fi
+
 # network (from: http://dzen.geekmode.org/dwiki/doku.php?id=dzen:network-meter)
 # cpu (from: https://bbs.archlinux.org/viewtopic.php?pid=661641#p661641)
-find_connected_if
+nwInterfaceStats=$(find_connected_if_stats)
 rx_old=$(cat $nwInterfaceStats/rx_bytes)
 tx_old=$(cat $nwInterfaceStats/tx_bytes)
 
 
 while true; do
-    find_connected_if
-    # get new cpu idle and total usage
-    eval "$(awk '/^cpu /{print "cpu_idle_now=" $5 "; cpu_total_now=" $2+$3+$4+$5 }' /proc/stat)"
-    cpu_interval=$((cpu_total_now-${cpu_total_old:-0}))
-    # calculate cpu usage (%)
-    let cpu_used="100 * ($cpu_interval - ($cpu_idle_now-${cpu_idle_old:-0})) / $cpu_interval"
+  nwInterfaceStats="$(find_connected_if_stats)"
 
-    # get new rx/tx counts
-    rx_now=$(cat $nwInterfaceStats/rx_bytes)
-    tx_now=$(cat $nwInterfaceStats/tx_bytes)
-    # calculate the rate (K) and total (M)
-    rx_rate=$(convertTxRates $(($rx_now-$rx_old)))
-    tx_rate=$(convertTxRates $(($tx_now-$tx_old)))
-    #  let rx_total=$rx_now/1048576
-    #  let tx_total=$tx_now/1048576
+  # get new cpu idle and total usage
+  eval "$(awk '/^cpu /{print "cpu_idle_now=" $5 "; cpu_total_now=" $2+$3+$4+$5 }' /proc/stat)"
+  cpu_interval=$((cpu_total_now-${cpu_total_old:-0}))
+  # calculate cpu usage (%)
+  let cpu_used="100 * ($cpu_interval - ($cpu_idle_now-${cpu_idle_old:-0})) / $cpu_interval"
 
-    # output vars
-    print_cpu_used() {
-        printf "%-14b" "${colour_dgry}${sep_solid}${colour_blu} ${glyph_cpu} ${cpu_used}%"
-    }
-    print_rx_rate() {
-        printf "%-15b" "${colour_blk}${sep_solid}${colour_grn} ${glyph_dl} ${rx_rate}"
-    }
-    print_tx_rate() {
-        printf "%-14b" "${colour_gry}${sep_line}${colour_red} ${glyph_ul} ${tx_rate}"
-    }
+  # get new rx/tx counts
+  rx_now=$(cat $nwInterfaceStats/rx_bytes)
+  tx_now=$(cat $nwInterfaceStats/tx_bytes)
+  # calculate the rate (K) and total (M)
+  rx_rate=$(convertTxRates $(($rx_now-$rx_old)))
+  tx_rate=$(convertTxRates $(($tx_now-$tx_old)))
+  #  let rx_total=$rx_now/1048576
+  #  let tx_total=$tx_now/1048576
 
-    # Pipe to status bar, not indented due to printing extra spaces/tabs
-    xsetroot -name "$(print_song_info)\
-    $(print_email_unread)\
-    $(print_cpu_used)$(print_mem_used)\
-    $(print_rx_rate)$(print_tx_rate)\
-    $(print_volume)\
-    $(print_datetime)"
-    # orig:
-        # xsetroot -name "$(print_song_info)\
-        #$(print_torrent_status)\
-        #$(print_email_unread)\
-        #$(print_last_msg)\
-        #$(print_cpu_used)$(print_mem_used)\
-        #$(print_rx_rate)$(print_tx_rate)\
-        #$(print_volume)\
-        #$(print_datetime)"
+  # output vars
+  print_cpu_used() {
+    printf "%-14b" "${colour_dgry}${sep_solid}${colour_blu} ${glyph_cpu} ${cpu_used}%"
+  }
+  print_rx_rate() {
+    printf "%-15b" "${colour_blk}${sep_solid}${colour_grn} ${glyph_dl} ${rx_rate}"
+  }
+  print_tx_rate() {
+    printf "%-14b" "${colour_gry}${sep_line}${colour_red} ${glyph_ul} ${tx_rate}"
+  }
 
-    # reset old rates
-    rx_old=$rx_now
-    tx_old=$tx_now
-    cpu_idle_old=$cpu_idle_now
-    cpu_total_old=$cpu_total_now
-    # loop stats every 1 second
-    sleep 1
+  # Pipe to status bar, not indented due to printing extra spaces/tabs
+  xsetroot -name "$(print_song_info)\
+$(print_email_unread)\
+$(print_cpu_used)$(print_mem_used)\
+$(print_rx_rate)$(print_tx_rate)\
+$(print_volume)\
+$(print_datetime)"
+  # orig:
+    # xsetroot -name "$(print_song_info)\
+    #$(print_torrent_status)\
+    #$(print_email_unread)\
+    #$(print_last_msg)\
+    #$(print_cpu_used)$(print_mem_used)\
+    #$(print_rx_rate)$(print_tx_rate)\
+    #$(print_volume)\
+    #$(print_datetime)"
+
+  # reset old rates:
+  rx_old=$rx_now
+  tx_old=$tx_now
+  cpu_idle_old=$cpu_idle_now
+  cpu_total_old=$cpu_total_now
+  # loop stats every 1 second:
+  sleep 1
 done
